iamDiyorjon/Najot-Booking

- Coworking-Booking.Api/Brokers/Storages/IStorageBroker.Order.cs
- Coworking-Booking.Api/Brokers/Storages/StorageBroker.Order.cs
> BROKERS: Insert Order

- Coworking-Booking.Api/Brokers/Storages/IStorageBroker.Order.cs
- Coworking-Booking.Api/Brokers/Storages/StorageBroker.Order.cs
> BROKERS: Select All Orders

- Coworking-Booking.Api/Brokers/Storages/IStorageBroker.Order.cs
- Coworking-Booking.Api/Brokers/Storages/StorageBroker.Order.cs
> BROKERS: Select Order By Id

- Coworking-Booking.Api/Brokers/Storages/IStorageBroker.Order.cs
- Coworking-Booking.Api/Brokers/Storages/StorageBroker.Order.cs
> BROKERS: Order Update

- Coworking-Booking.Api/Brokers/Storages/IStorageBroker.Order.cs
- Coworking-Booking.Api/Brokers/Storages/StorageBroker.Order.cs
> BROKERS: Delete Order

- NajotBooking.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Exceptions.Modify.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Logic.Modify.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Validations.Add.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Validations.Modify.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.cs
- NajotBooking.Api/Services/Foundations/Users/UserService.cs
> FOUNDATIONS: Upgrade User Modify

- NajotBooking.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Exeptions.RemoveById.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Logic.RemoveById.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Validations.RemoveById.cs
- NajotBooking.Api/Services/Foundations/Users/IUserService.cs
- NajotBooking.Api/Services/Foundations/Users/UserService.cs
> FOUNDATIONS: Upgrade Remove User

- NajotBooking.Api.Tests.Unit/Services/Foundations/Seats/SeatServiceTests.Exceptions.Add.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Seats/SeatServiceTests.Logic.Add.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Seats/SeatServiceTests.Validations.Add.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Seats/SeatServiceTests.cs
- NajotBooking.Api/Models/Seats/Branch.cs
- NajotBooking.Api/Models/Seats/Exceptions/InvalidSeatException.cs
- NajotBooking.Api/Models/Seats/Exceptions/LockedSeatException.cs
- NajotBooking.Api/Models/Seats/Seat.cs
- NajotBooking.Api/Services/Foundations/Seats/SeatService.Exception.cs
- NajotBooking.Api/Services/Foundations/Seats/SeatService.Validation.cs
> FOUNDATIONS: Upgrade Add Seat

- NajotBooking.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Exceptions.RetrieveAll.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Logic.RetrieveAll.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.cs
- NajotBooking.Api/Services/Foundations/Users/UserService.cs
> FOUNDATIONS: Upgrade Retrieve All Users

- NajotBooking.Api.Tests.Unit/Services/Foundations/Seats/SeatServiceTests.Exceptions.RerieveAll.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Seats/SeatServiceTests.Logic.RetrieveAll.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Seats/SeatServiceTests.cs
- NajotBooking.Api/Services/Foundations/Seats/SeatService.cs
> FOUNDATIONS: Upgrade Retrieve All Seats 

- NajotBooking.Api.Tests.Unit/Services/Foundations/Orders/OrderServiceTests.Exceptions.RemoveById.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Orders/OrderServiceTests.Logic.RemoveById.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Orders/OrderServiceTests.Validations.RemoveById.cs
- NajotBooking.Api/Brokers/Storages/IStorageBroker.Order.cs
- NajotBooking.Api/Brokers/Storages/StorageBroker.Order.cs
- NajotBooking.Api/Models/Orders/Exceptions/NotFoundOrderException.cs
- NajotBooking.Api/Services/Foundations/Orders/IOrderService.cs
- NajotBooking.Api/Services/Foundations/Orders/OrderService.Exceptions.cs
- NajotBooking.Api/Services/Foundations/Orders/OrderService.Validations.cs
- NajotBooking.Api/Services/Foundations/Orders/OrderService.cs
> FOUNDATIONS: Remove Order

- Coworking-Booking.Api/Services/Foundations/Orders/IOrderService.cs
- Coworking-Booking.Api/Services/Foundations/Orders/OrderService.Exception.cs
- Coworking-Booking.Api/Services/Foundations/Orders/OrderService.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Orders/OrderServiceTests.Exceptions.RetrieveAll.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Orders/OrderServiceTests.Logic.RetrieveAll.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Orders/OrderServiceTests.cs
- NajotBooking.Api/Services/Foundations/Orders/IOrderService.cs
- NajotBooking.Api/Services/Foundations/Orders/OrderService.Exceptions.cs
- NajotBooking.Api/Services/Foundations/Orders/OrderService.cs
- NajotBooking.Api/Services/Foundations/Orders/OrderServiceTests.Logic.RetrieveAll
> FOUNDATIONS: Retrieve All Orders

- NajotBooking.Api/Controllers/SeatsController.cs
> EXPOSERS: Seats Post Upgrade

- NajotBooking.Api/Controllers/SeatsController.cs
> EXPOSERS: Upgrade Get All Seats

- NajotBooking.Api/Controllers/SeatsController.cs
> EXPOSERS: Upgrade Seat Get By Id

- NajotBooking.Api.Tests.Unit/Services/Foundations/Orders/OrderServiceTests.Exceptions.RetrieveById.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Orders/OrderServiceTests.Logic.RetrieveById.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Orders/OrderServiceTests.Validations.RetrieveById.cs
- NajotBooking.Api/Services/Foundations/Orders/IOrderService.cs
- NajotBooking.Api/Services/Foundations/Orders/OrderService.cs
- NajotBooking.Api/Services/Foundations/Orders/OrderServiceTests.Logic.RetrieveAll
> FOUNDATIONS: Retrieve Order By Id

- NajotBooking.Api.Tests.Unit/Services/Foundations/Seats/SeatServiceTests.Exceptions.Modify.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Seats/SeatServiceTests.Logic.Modify.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Seats/SeatServiceTests.Validations.Modify.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Seats/SeatServiceTests.cs
- NajotBooking.Api/Services/Foundations/Seats/SeatService.Exception.cs
- NajotBooking.Api/Services/Foundations/Seats/SeatService.Validation.cs
- NajotBooking.Api/Services/Foundations/Seats/SeatService.cs
- NajotBooking.Api/Startup.cs
- NajotBooking.Api/appsettings.Development.json
> FOUNDATIONS: Upgrade Modify Seat

- NajotBooking.Api/Controllers/SeatsController.cs
> EXPOSERS: Seats Put

- NajotBooking.Api.Tests.Unit/Services/Foundations/Seats/SeatServiceTests.Exceptions.RemoveById.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Seats/SeatServiceTests.Logic.RemoveById.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Seats/SeatServiceTests.Validations.RemoveById.cs
- NajotBooking.Api/Controllers/SeatsController.cs
- NajotBooking.Api/Services/Foundations/Seats/ISeatService.cs
- NajotBooking.Api/Services/Foundations/Seats/SeatService.cs
> FOUNDATIONS: Upgrade Remove Seat

- NajotBooking.Api/Controllers/HomeController.cs
- NajotBooking.Api/Controllers/SeatsController.cs
- NajotBooking.Api/Controllers/UsersController.cs
> EXPOSERS: Upgrade Delete Seat

- NajotBooking.Api/Controllers/UsersController.cs
- NajotBooking.Api/Startup.cs
> EXPOSERS: Upgrade CRUD User 

- NajotBooking.Api/Controllers/OrdersController.cs
> EXPOSERS: Post Order

- NajotBooking.Api/Controllers/OrdersController.cs
> EXPOSERS: Orders Get All

- NajotBooking.Api/Controllers/OrdersController.cs
> EXPOSERS: Get Order By Id

- NajotBooking.Api/Controllers/OrdersController.cs
> EXPOSERS: Delete Order

- NajotBooking.Api.Tests.Unit/Services/Foundations/Orders/OrderServiceTests.Exceptions.Modify.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Orders/OrderServiceTests.Logic.Modify.cs
- NajotBooking.Api.Tests.Unit/Services/Foundations/Orders/OrderServiceTests.Validations.Modify.cs
- NajotBooking.Api/Services/Foundations/Orders/IOrderService.cs
- NajotBooking.Api/Services/Foundations/Orders/OrderService.Exceptions.cs
- NajotBooking.Api/Services/Foundations/Orders/OrderService.Validations.cs
- NajotBooking.Api/Services/Foundations/Orders/OrderService.cs
> FOUNDATIONS: Modify Order

- NajotBooking.Api/Controllers/OrdersController.cs
> EXPOSERS: PUT Order
